"""empty message

Revision ID: 750cdc702a91
Revises: 7db66d4b0914
Create Date: 2021-10-09 15:00:00.008005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750cdc702a91'
down_revision = '7db66d4b0914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'coupon', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coupon', type_='unique')
    # ### end Alembic commands ###
